---
title: "Lottery Simulation Code"
author: "Richard Zheng, Stephen Haslett"
date: "2/7/2022"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
library(tidyverse)
library(kableExtra)
```



```{r, helperFunctions, echo = FALSE, message = FALSE, warning = FALSE}
#' Simulates generating Mega Millions lottery tickets containing random numbers.
#'
#' This function returns a list containing 5 unique numbers from 1 to 70, and 1 number from
#' 1 to 25 for the Megaball, in order to simulate a valid Mega Millions lottery ticket.
#'
#' @param numbers Numeric: Random numbers to be used for the ticket base numbers.
#'
#' @param megaball Numeric: Random number to be used for the Mega Ball.
#'
#' @return List: A list containing 7 random numbers representing a Mega Millions lottery ticket.
#'
#' @export
random_ticket_generator = function(numbers, megaball) {
  ticket = sample(numbers, 5, replace = FALSE)
  ball = sample(megaball, 1, replace = FALSE)
  return(list('numbers' = ticket, 'megaball' = ball))
}
  

#' Calculates the cost of a lottery ticket.
#'
#' @param multiplier Optional Boolean: TRUE if the multiplier cost should be applied to the ticket cost, FALSE otherwise.
#'
#' @return List: A list containing the cost of a lottery ticket.
#'
#' @export
calculate_ticket_cost = function(multiplier = FALSE) {
  cost = 2
  multi = 1
  if (multiplier == TRUE) {
    cost = cost + 1
    multi = sample(2:5, 1)
  }
  return(list('cost' = cost,'multiplier' = multi))
}


#' Compares simulated lottery ticket numbers with winning numbers to calculate the amount of matching numbers present.
#'
#' @param ticket Numeric: The lottery ticket numbers under comparison.
#'
#' @param win_nums Numeric: The winning lottery numbers to compare against.
#'
#' @return List: A list containing the total number of matching base and mega ball numbers.
#'
#' @export
numbers_matched = function(ticket, win_nums) {
  megaball = 0
  matched = 0
  if (ticket$megaball == win_nums$megaball) {
    megaball = 1
  }
  for (num in ticket$numbers) {
    for (target in win_nums$numbers) {
      if (num == target) {
        matched = matched + 1
      }
    }
  }
  return(list('match'= matched,'megaball'= megaball))
}


#' Calculates the payout for a lottery game based on the amount of matching numbers obtained.
#'
#' @param num_match Numeric: The number of matching winning numbers.
#'
#' @param mega_match Boolean: TRUE if the Mega Ball was matched, FALSE otherwise.
#'
#' @return Numeric: Total winning dollar amount based on numbers matched.
#'
#' @export
calculate_winnings = function(num_match, mega_match) {
  if (mega_match == 1) {
    if (num_match == 0) {
      return(2)
    }
    else if (num_match == 1) {
      return(4)
    }
    else if (num_match == 2) {
      return(10)
    }
    else if (num_match == 3) {
      return(200)
    }
    else if (num_match == 4) {
      return(10000)
    }
    else {
      return(10000000)  
    }
  }
  else {
    if (num_match < 3) {
      return(0)
    }
    else if (num_match == 3) {
      return(10)
    }
    else if (num_match == 4) {
      return(500)
    }
    else {
      return(1000000)
    }
  }
}
```



```{r, ticketGenerators, echo = FALSE, message = FALSE, warning = FALSE}
#' Generates and returns a lottery ticket along with its cost.
#'
#' @param numbers Numeric: The base numbers to be included in the ticket.
#'
#' @param megaball Numeric: The Mega Ball number to be included in the ticket..
#'
#' @return List: A list containing ticket base numbers, Mega Ball, ticket cost,
#' and multiplier number when "multi" is equal to TRUE.
#'
#' @export
ticket_generator = function(numbers, megaball, multi = FALSE) {
  ticket = random_ticket_generator(numbers, megaball)
  ticket_cost = calculate_ticket_cost(multiplier = multi)
  return(c(ticket, ticket_cost))
}


#' Responsible for generating the winning numbers against which lottery tickets are compared.
#'
#' @return List: A list of simulated winning numbers.
#'
#' @export
winning_numbers_generator = function() {
  return (ticket_generator(1:70, 1:25, multi = TRUE))
}
```



```{r, singleTicketComparison, echo = FALSE, message = FALSE, warning = FALSE}
#  Compares a single random ticket against n winning tickets.
#'
#' @param trails Numeric: The number of trails to perform the comparison for.
#'
#' @param m Optional Boolean: Whether or not the multiplier number should be included in the comparison.
#'
#' @return List: A list containing average numbers and megaball numbers, cost and winnings per n trails.
#'
#' @export
single_ticket_comparison = function(trials, m = FALSE) {
  nums = 0
  megas = 0
  cost = 0
  win = c()
  multiplier = 1
  ticket = ticket_generator(1:70, 1:25, multi = m)
  for (i in 1:trials) {
    winning_numbers = winning_numbers_generator()
    if (m == TRUE) {
      if (winning_numbers$multiplier == ticket$multiplier) {
        multiplier = ticket$multiplier
      }
      else {
        multiplier = 1
      }
    }
    match = numbers_matched(ticket, winning_numbers)
    nums = nums + match$match
    megas = megas + match$megaball
    cost = cost + ticket$cost
    win = c(win, (calculate_winnings(match$match, match$megaball)*multiplier)-ticket$cost)
  }
  return(list('avg_nums' = nums/trials, 'avg_megas' = megas/trials, 'cost' = cost, 'winnings' = win))
}
```



```{r, multipleTicketComparison, echo = FALSE, message = FALSE, warning = FALSE}
#  Compares n random tickets against n winning tickets.
#'
#' @param trails Numeric: The number of trails to perform the comparison for.
#'
#' @param m Optional Boolean: Whether or not the multiplier number should be included in the comparison.
#'
#' @return List: A list containing average numbers and megaball numbers, cost and winnings per n trails.
#'
#' @export
multiple_ticket_comparison = function(trials, m = FALSE) {
  nums = 0
  megas = 0
  cost = 0
  win = c()
  multiplier = 1
  for (i in 1:trials) {
    ticket = ticket_generator(1:70, 1:25, multi = m)
    winning_numbers = winning_numbers_generator()
    if (m == TRUE) {
      if (winning_numbers$multiplier == ticket$multiplier) {
        multiplier = ticket$multiplier
      }
      else {
        multiplier = 1
      }
    }
    match = numbers_matched(ticket, winning_numbers)
    nums = nums + match$match
    megas = megas + match$megaball
    cost = cost + ticket$cost
    win = c(win, (calculate_winnings(match$match, match$megaball)*multiplier)-ticket$cost)
  }
  return(list('avg_nums' = nums/trials, 'avg_megas' = megas/trials, 'cost' = cost, 'winnings' = win))
}
```



```{r, baseCase, echo = FALSE, message = FALSE, warning = FALSE}
# Generate base case results.
base_case = single_ticket_comparison(10000, m = FALSE)
base_winnings = base_case$winnings
```



```{r, tTest, echo = FALSE, message = FALSE, warning = FALSE}
# Comparison of base case Vs. Multiplier strategy.
with_multi = single_ticket_comparison(10000, m = TRUE)
multi_winnings = with_multi$winnings
multi_test = t.test(base_winnings, multi_winnings, alternative = c('two.sided'))
multi_test
```



```{r, randomTTest, echo = FALSE, message = FALSE, warning = FALSE}
# Comparison of base case Vs. Random Numbers strategy.
with_random = multiple_ticket_comparison(10000, m = FALSE)
random_winnings = with_random$winnings

random_test = t.test(base_winnings, random_winnings, alternative = c('two.sided'))
random_test
```



```{r dataImport, echo = FALSE, message = FALSE, warning = FALSE}
# Import "Winning Mega Millions lottery numbers from 2002" dataset from NY Open Data.
megaMillionsDataURL <- "https://data.ny.gov/resource/5xaw-6ayf.csv"
megaMillionsWinningNumbers <- read.csv(megaMillionsDataURL)
megaMillionsWinningNumbers %>% head()
```



```{r, winningNumberOccurrences, echo = FALSE, message = FALSE, warning = FALSE}
#' Counts the amount of winning base numbers in a ticket.
#'
#' @param winning_tickets Numeric: The tickets containing the winning numbers to be counted.
#'
#' @return Dataframe: A dataframe containing counts of winning numbers.
#'
#' @export
winningNumberOccurrence = function(winning_tickets) {
  winning_numbers = c()
  for (ticket in winning_tickets) {
    winning_numbers = c(winning_numbers,str_split(ticket, pattern = ' ')[[1]])
  }
  number_counts = data.frame(numbers = winning_numbers) %>%
    group_by(numbers) %>%
    summarize(count = n()) %>%
    arrange(-count)
    
  return(number_counts)
}

#' Counts the amount of winning Mega Ball numbers in a ticket.
#'
#' @param winning_tickets Numeric: A ticket containing the winning Mega Ball numbers to be counted.
#'
#' @return Dataframe: A dataframe containing counts of winning Mega Ball numbers.
#'
#' @export
megaballOccurrence = function(megaballs) {
  number_counts = data.frame(numbers = megaballs) %>%
    group_by(numbers) %>%
    summarize(count = n()) %>%
    arrange(-count)
  
  return(number_counts)
}
```



```{r, hotColdNumbers, echo = FALSE, message = FALSE, warning = FALSE}
# Run through the NY Open Data's historic winning Mega Millions data set to find the
# Most frequently occurring  winning numbers and Mega Balls (hot numbers), and least
# frequently occurring numbers (cold numbers). 
number_counts = winningNumberOccurrence(megaMillionsWinningNumbers$winning_numbers)
megaball_counts = megaballOccurrence(megaMillionsWinningNumbers$mega_ball)

# Most frequently occurring numbers.
hot_numbers = number_counts %>% filter(count >= mean(count))
hot_megaballs = megaball_counts %>% filter(count >= mean(count))

# Least frequently occurring numbers.
cold_numbers = number_counts %>% filter(count < mean(count))
cold_megaballs = megaball_counts %>% filter(count < mean(count))
```



```{r, barCharts, echo = FALSE, message = FALSE, warning = FALSE, fig.width = 12, fig.height = 7}
#' Plots bar charts and organizes the data in descending order.
#'
#' @param dataset Numeric: The dataset containing the data that should be plotted as a bar chart.
#'
#' @param title String: The title of the bar chart.
#'
#' @return List: The rendered bar chart.
#'
#' @export
chart_plotter = function(dataset, title) {
  dataset %>%
  ggplot(aes(x = reorder(numbers, -count), y = count, fill = count)) +
  geom_bar(stat = 'identity') +
  labs(x = 'Number', y = 'Count', title = title) +
  theme_minimal() +
  theme(plot.title = element_text(size = 20),
        axis.text = element_text(size = 12),
        axis.title = element_text(size = 18))
}

chart_plotter(hot_numbers,'Most Recurring Lottery Numbers')
chart_plotter(cold_numbers,'Least Recurring Lottery Numbers')
chart_plotter(hot_megaballs,'Most Recurring Megaball Numbers')
chart_plotter(cold_megaballs,'Least Recurring Megaball Numbers')
```



```{r, hotHandFallacy, echo = FALSE, message = FALSE, warning = FALSE}
#  Responsible for comparing Hot Hand and Gambler's Fallacy based tickets against n winning tickets.
#'
#' @param trails Numeric: The number of trails to perform the comparison for.
#'
#' @param n_choices Numeric: THe base numbers to compare.
#'
#' @param mb_choices Numeric: The Mega Ball numbers to compare.
#'
#' @param m Optional Boolean: Whether or not the multiplier number should be included in the comparison.
#'
#' @return List: A list containing average numbers and megaball numbers, cost and winnings per n trails.
#'
#' @export
fallacy_cases = function(trials, n_choices, mb_choices, m = FALSE) {
  nums = 0
  megas = 0
  cost = 0
  win = c()
  multiplier = 1
  ticket = ticket_generator(n_choices, mb_choices, multi = m)
  for (i in 1:trials) {
    winning_numbers = winning_numbers_generator()
    if (m == TRUE) {
      if (winning_numbers$multiplier == ticket$multiplier) {
        multiplier = ticket$multiplier
      } else {
        multiplier = 1
      }
    }
    match = numbers_matched(ticket, winning_numbers)
    nums = nums + match$match
    megas = megas + match$megaball
    cost = cost + ticket$cost
    win = c(win, (calculate_winnings(match$match, match$megaball)*multiplier)-ticket$cost)
  }
  
  return(list('avg_nums' = nums/trials, 'avg_megas' = megas/trials, 'cost' = cost, 'winnings' = win))
}

hot_hand = fallacy_cases(10000, hot_numbers$numbers, hot_megaballs$numbers, m = FALSE)
hot_winnings = hot_hand$winnings

hot_hand_test = t.test(base_winnings, hot_winnings, alternative = c('two.sided'))
hot_hand_test
```


```{r,  gamblersFallacy, echo = FALSE, message = FALSE, warning = FALSE}
# Generate results for Least Frequent Numbers strategy (Gambler's Fallacy).
gambler_fallacy = fallacy_cases(10000, cold_numbers$numbers, cold_megaballs$numbers, m = FALSE)
gambler_winnings = gambler_fallacy$winnings
gambler_fallacy_test = t.test(base_winnings, gambler_winnings, alternative = c('two.sided'))
gambler_fallacy_test
```



```{r, comparisonCharts, echo = FALSE, message = FALSE, warning = FALSE}
#' Plots the distribution of the base case Vs. the comparison case.
#'
#' @param dist1 Double: The winnings from the base case.
#'
#' @param dist2 Double: The winnings from the comparison case.
#'
#' @param title String: The title of the distribution chart.
#'
#' @return List: The rendered distribution chart.
#'
#' @export
compare_dist = function(dist1, dist2, title) {
  colors = c(
    'Base Case' = 'blue',
    'Other Case' = 'red'
  )
  se1 = sd(dist1)/sqrt(length(dist1))
  se2 = sd = sd(dist2)/sqrt(length(dist2))
  normal_dist1 = data.frame(x1 = rnorm(n = 10000, mean = mean(dist1), sd = se1))
  normal_dist2 = data.frame(x1 = rnorm(n = 10000, mean = mean(dist2), sd = se2))
  normal_dist1 %>%
    ggplot(aes(x1, color = 'Base Case')) + geom_histogram(alpha = 0.1, bins = 50) +
    geom_histogram(data = normal_dist2,aes(x1, color = 'Other Case'), alpha = 0.1, bins = 50) +
    labs(x = 'Winnings', y = 'Count', title = title, color = 'Legend') +
    scale_color_manual(values = colors)
}

compare_dist(base_winnings,
             multi_winnings,
            'Base Case Vs Multiplier Strategy')

compare_dist(base_winnings,
             random_winnings,
            'Base Case Vs Random Numbers Strategy')

compare_dist(base_winnings,
             hot_winnings,
            'Base Case Vs Most Frequent Numbers Strategy')

compare_dist(base_winnings,
             gambler_winnings,
            'Base Case Vs Least Frequent Numbers Strategy')
```



```{r, averageWinnings, echo = FALSE, message = FALSE, warning = FALSE}
# Generate the "Comparison Of Results" table.
average_winnings = data.frame(
  c('Consistent Numbers Strategy (_Base Case_)',
    'Multiplier Strategy',
    'Random Numbers Strategy',
    'Most Frequent Numbers Strategy (_Hot Hand Fallacy_)',
    'Least Frequent Numbers Strategy (_Gambler\'s Fallacy_)'),
  c(base_winnings %>% mean(), multi_winnings %>% mean(), random_winnings %>% mean(), hot_winnings %>% mean(), gambler_winnings %>% mean()),
  c(base_winnings %>% sd(), multi_winnings %>% sd(), random_winnings %>% sd(), hot_winnings %>% sd(), gambler_winnings %>% sd())
  )

colnames(average_winnings) = c('Strategy', 'Average Winnings', 'Standard Deviation')

kable(average_winnings, 'html', escape = F, caption = '<center><h3>Average Winnings</h3></center>',
      col.names = c('Strategy', 'Average Winnings', 'Standard Deviation')) %>%
  column_spec(1:3, bold = F) %>%
  kable_styling('striped') %>%
  scroll_box(width = '100%', height = 'auto')
```


